image: flowhealth/go_buildtools:1.3
script:
  - gpm 
  - go test -v ./aws/
  - go test -v ./cloudwatch/
  - go test -v ./dynamodb/
  - go test -v ./ec2/
  - go test -v ./elb/
  - go test -v ./iam/
  - go test -v ./s3/
  - go test -v ./sqs/
  - go test -v ./autoscaling/
  - go test -v ./rds/

notify:
  email:
    recipients:
      - viktor@flowhealth.com
