package aws

var USGovWest = Region{
	Name:                   "us-gov-west-1",
	EC2Endpoint:            "https://ec2.us-gov-west-1.amazonaws.com",
	S3Endpoint:             "https://s3-fips-us-gov-west-1.amazonaws.com",
	S3BucketEndpoint:       "",
	S3LocationConstraint:   true,
	S3LowercaseBucket:      true,
	SDBEndpoint:            "",
	SNSEndpoint:            "https://sns.us-gov-west-1.amazonaws.com",
	SQSEndpoint:            "https://sqs.us-gov-west-1.amazonaws.com",
	SESEndpoint:            "",
	IAMEndpoint:            "https://iam.us-gov.amazonaws.com",
	ELBEndpoint:            "https://elasticloadbalancing.us-gov-west-1.amazonaws.com",
	DynamoDBEndpoint:       "https://dynamodb.us-gov-west-1.amazonaws.com",
	CloudWatchServicepoint: ServiceInfo{"https://monitoring.us-gov-west-1.amazonaws.com", V2Signature},
	AutoScalingEndpoint:    "https://autoscaling.us-gov-west-1.amazonaws.com",
	RDSEndpoint:            ServiceInfo{"https://rds.us-gov-west-1.amazonaws.com", V2Signature},
	KinesisEndpoint:        "",
}

var USEast = Region{
	Name:                   "us-east-1",
	EC2Endpoint:            "https://ec2.us-east-1.amazonaws.com",
	S3Endpoint:             "https://s3.amazonaws.com",
	S3BucketEndpoint:       "",
	S3LocationConstraint:   false,
	S3LowercaseBucket:      false,
	SDBEndpoint:            "https://sdb.amazonaws.com",
	SNSEndpoint:            "https://sns.us-east-1.amazonaws.com",
	SQSEndpoint:            "https://sqs.us-east-1.amazonaws.com",
	SESEndpoint:            "https://email.us-east-1.amazonaws.com",
	IAMEndpoint:            "https://iam.amazonaws.com",
	ELBEndpoint:            "https://elasticloadbalancing.us-east-1.amazonaws.com",
	DynamoDBEndpoint:       "https://dynamodb.us-east-1.amazonaws.com",
	CloudWatchServicepoint: ServiceInfo{"https://monitoring.us-east-1.amazonaws.com", V2Signature},
	AutoScalingEndpoint:    "https://autoscaling.us-east-1.amazonaws.com",
	RDSEndpoint:            ServiceInfo{"https://rds.us-east-1.amazonaws.com", V2Signature},
	KinesisEndpoint:        "https://kinesis.us-east-1.amazonaws.com",
}

var USWest = Region{
	Name:                   "us-west-1",
	EC2Endpoint:            "https://ec2.us-west-1.amazonaws.com",
	S3Endpoint:             "https://s3-us-west-1.amazonaws.com",
	S3BucketEndpoint:       "",
	S3LocationConstraint:   true,
	S3LowercaseBucket:      true,
	SDBEndpoint:            "https://sdb.us-west-1.amazonaws.com",
	SNSEndpoint:            "https://sns.us-west-1.amazonaws.com",
	SQSEndpoint:            "https://sqs.us-west-1.amazonaws.com",
	SESEndpoint:            "",
	IAMEndpoint:            "https://iam.amazonaws.com",
	ELBEndpoint:            "https://elasticloadbalancing.us-west-1.amazonaws.com",
	DynamoDBEndpoint:       "https://dynamodb.us-west-1.amazonaws.com",
	CloudWatchServicepoint: ServiceInfo{"https://monitoring.us-west-1.amazonaws.com", V2Signature},
	AutoScalingEndpoint:    "https://autoscaling.us-west-1.amazonaws.com",
	RDSEndpoint:            ServiceInfo{"https://rds.us-west-1.amazonaws.com", V2Signature},
	KinesisEndpoint:        "",
}

var USWest2 = Region{
	Name:                   "us-west-2",
	EC2Endpoint:            "https://ec2.us-west-2.amazonaws.com",
	S3Endpoint:             "https://s3-us-west-2.amazonaws.com",
	S3BucketEndpoint:       "",
	S3LocationConstraint:   true,
	S3LowercaseBucket:      true,
	SDBEndpoint:            "https://sdb.us-west-2.amazonaws.com",
	SNSEndpoint:            "https://sns.us-west-2.amazonaws.com",
	SQSEndpoint:            "https://sqs.us-west-2.amazonaws.com",
	SESEndpoint:            "https://email.us-west-2.amazonaws.com",
	IAMEndpoint:            "https://iam.amazonaws.com",
	ELBEndpoint:            "https://elasticloadbalancing.us-west-2.amazonaws.com",
	DynamoDBEndpoint:       "https://dynamodb.us-west-2.amazonaws.com",
	CloudWatchServicepoint: ServiceInfo{"https://monitoring.us-west-2.amazonaws.com", V2Signature},
	AutoScalingEndpoint:    "https://autoscaling.us-west-2.amazonaws.com",
	RDSEndpoint:            ServiceInfo{"https://rds.us-west-2.amazonaws.com", V2Signature},
	KinesisEndpoint:        "https://kinesis.us-west-2.amazonaws.com",
}

var EUWest = Region{
	Name:                   "eu-west-1",
	EC2Endpoint:            "https://ec2.eu-west-1.amazonaws.com",
	S3Endpoint:             "https://s3-eu-west-1.amazonaws.com",
	S3BucketEndpoint:       "",
	S3LocationConstraint:   true,
	S3LowercaseBucket:      true,
	SDBEndpoint:            "https://sdb.eu-west-1.amazonaws.com",
	SNSEndpoint:            "https://sns.eu-west-1.amazonaws.com",
	SQSEndpoint:            "https://sqs.eu-west-1.amazonaws.com",
	SESEndpoint:            "https://email.eu-west-1.amazonaws.com",
	IAMEndpoint:            "https://iam.amazonaws.com",
	ELBEndpoint:            "https://elasticloadbalancing.eu-west-1.amazonaws.com",
	DynamoDBEndpoint:       "https://dynamodb.eu-west-1.amazonaws.com",
	CloudWatchServicepoint: ServiceInfo{"https://monitoring.eu-west-1.amazonaws.com", V2Signature},
	AutoScalingEndpoint:    "https://autoscaling.eu-west-1.amazonaws.com",
	RDSEndpoint:            ServiceInfo{"https://rds.eu-west-1.amazonaws.com", V2Signature},
	KinesisEndpoint:        "https://kinesis.eu-west-1.amazonaws.com",
}

var APSoutheast = Region{
	Name:                   "ap-southeast-1",
	EC2Endpoint:            "https://ec2.ap-southeast-1.amazonaws.com",
	S3Endpoint:             "https://s3-ap-southeast-1.amazonaws.com",
	S3BucketEndpoint:       "",
	S3LocationConstraint:   true,
	S3LowercaseBucket:      true,
	SDBEndpoint:            "https://sdb.ap-southeast-1.amazonaws.com",
	SNSEndpoint:            "https://sns.ap-southeast-1.amazonaws.com",
	SQSEndpoint:            "https://sqs.ap-southeast-1.amazonaws.com",
	SESEndpoint:            "",
	IAMEndpoint:            "https://iam.amazonaws.com",
	ELBEndpoint:            "https://elasticloadbalancing.ap-southeast-1.amazonaws.com",
	DynamoDBEndpoint:       "https://dynamodb.ap-southeast-1.amazonaws.com",
	CloudWatchServicepoint: ServiceInfo{"https://monitoring.ap-southeast-1.amazonaws.com", V2Signature},
	AutoScalingEndpoint:    "https://autoscaling.ap-southeast-1.amazonaws.com",
	RDSEndpoint:            ServiceInfo{"https://rds.ap-southeast-1.amazonaws.com", V2Signature},
	KinesisEndpoint:        "https://kinesis.ap-southeast-1.amazonaws.com",
}

var APSoutheast2 = Region{
	Name:                   "ap-southeast-2",
	EC2Endpoint:            "https://ec2.ap-southeast-2.amazonaws.com",
	S3Endpoint:             "https://s3-ap-southeast-2.amazonaws.com",
	S3BucketEndpoint:       "",
	S3LocationConstraint:   true,
	S3LowercaseBucket:      true,
	SDBEndpoint:            "https://sdb.ap-southeast-2.amazonaws.com",
	SNSEndpoint:            "https://sns.ap-southeast-2.amazonaws.com",
	SQSEndpoint:            "https://sqs.ap-southeast-2.amazonaws.com",
	SESEndpoint:            "",
	IAMEndpoint:            "https://iam.amazonaws.com",
	ELBEndpoint:            "https://elasticloadbalancing.ap-southeast-2.amazonaws.com",
	DynamoDBEndpoint:       "https://dynamodb.ap-southeast-2.amazonaws.com",
	CloudWatchServicepoint: ServiceInfo{"https://monitoring.ap-southeast-2.amazonaws.com", V2Signature},
	AutoScalingEndpoint:    "https://autoscaling.ap-southeast-2.amazonaws.com",
	RDSEndpoint:            ServiceInfo{"https://rds.ap-southeast-2.amazonaws.com", V2Signature},
	KinesisEndpoint:        "https://kinesis.ap-southeast-2.amazonaws.com",
}

var APNortheast = Region{
	Name:                   "ap-northeast-1",
	EC2Endpoint:            "https://ec2.ap-northeast-1.amazonaws.com",
	S3Endpoint:             "https://s3-ap-northeast-1.amazonaws.com",
	S3BucketEndpoint:       "",
	S3LocationConstraint:   true,
	S3LowercaseBucket:      true,
	SDBEndpoint:            "https://sdb.ap-northeast-1.amazonaws.com",
	SNSEndpoint:            "https://sns.ap-northeast-1.amazonaws.com",
	SQSEndpoint:            "https://sqs.ap-northeast-1.amazonaws.com",
	SESEndpoint:            "",
	IAMEndpoint:            "https://iam.amazonaws.com",
	ELBEndpoint:            "https://elasticloadbalancing.ap-northeast-1.amazonaws.com",
	DynamoDBEndpoint:       "https://dynamodb.ap-northeast-1.amazonaws.com",
	CloudWatchServicepoint: ServiceInfo{"https://monitoring.ap-northeast-1.amazonaws.com", V2Signature},
	AutoScalingEndpoint:    "https://autoscaling.ap-northeast-1.amazonaws.com",
	RDSEndpoint:            ServiceInfo{"https://rds.ap-northeast-1.amazonaws.com", V2Signature},
	KinesisEndpoint:        "https://kinesis.ap-northeast-1.amazonaws.com",
}

var SAEast = Region{
	Name:                   "sa-east-1",
	EC2Endpoint:            "https://ec2.sa-east-1.amazonaws.com",
	S3Endpoint:             "https://s3-sa-east-1.amazonaws.com",
	S3BucketEndpoint:       "",
	S3LocationConstraint:   true,
	S3LowercaseBucket:      true,
	SDBEndpoint:            "https://sdb.sa-east-1.amazonaws.com",
	SNSEndpoint:            "https://sns.sa-east-1.amazonaws.com",
	SQSEndpoint:            "https://sqs.sa-east-1.amazonaws.com",
	SESEndpoint:            "",
	IAMEndpoint:            "https://iam.amazonaws.com",
	ELBEndpoint:            "https://elasticloadbalancing.sa-east-1.amazonaws.com",
	DynamoDBEndpoint:       "https://dynamodb.sa-east-1.amazonaws.com",
	CloudWatchServicepoint: ServiceInfo{"https://monitoring.sa-east-1.amazonaws.com", V2Signature},
	AutoScalingEndpoint:    "https://autoscaling.sa-east-1.amazonaws.com",
	RDSEndpoint:            ServiceInfo{"https://rds.sa-east-1.amazonaws.com", V2Signature},
	KinesisEndpoint:        "",
}
